### ISSUE TITLE
Doesnt work on the latest 1.19.2 with kubejs fluids

### ISSUE THREAD

**Issue by Xplodin** [North-West-Wind/MekanismFissionRecipe#12]
Falling back to vanilla: java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.getAsDouble()" because the return value of "com.google.gson.JsonObject.get(String)" is null
[01Apr2023 11:34:47.798] [Render thread/WARN] [KubeJS Server/]: Failed to parse recipe mekanism:coolant/beanactor[mekanism:fluid_coolant]: java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.getAsDouble()" because the return value of "com.google.gson.JsonObject.get(String)" is null

[beanpack.zip](https://github.com/North-West-Wind/MekanismFissionRecipe/files/11131342/beanpack.zip)

here is my script

**Comment by North-West-Wind** [comment]
The problem seems to be missing properties `thermalEnthalpy` and `conductivity` in the JSON file. Sorry that I forgot to put them in README.

If you don't know what to do with those 2 properties, just copy the ones from the [water coolant recipe](https://github.com/North-West-Wind/MekanismFissionRecipe/blob/main/src/main/resources/data/mekanism/recipes/coolant/water.json)

**Comment by ComfyEcho** [comment]
this is still an issue but with gas_coolant instead
